name: CI for React app

on:
  push:
    branches:
      - master  # or the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install -f

      - name: Run build
        run: npm run build
      
      - name: Run sitemap build
        run: npm run sitemapjs
